# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9f325120da68354b94dee23f65382ff031657ad92af8619911863df2c0ba757fdaf873dd002048a792a6157b2ce46acf7d90539ef2bc115fbbcc914c8e9e784

test:
  secret_key_base: 1db4c1daa4bda7cb1c1772f80cbf33846f3d3262f17ce3d4ccf1aae05a55def48eb1dfa09580685aa8b12deb575035f58ca78d24e1c753cfdd8b30867178145f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
